local_backend: true

logo_url: /images/logo/logo-2.png

backend:
    name: "github"
    repo: loicginoux/loicginoux
    branch: master
    base_url: https://sveltia-cms-auth.lginoux.workers.dev
    automatic_deployments: false

media_folder: "public/images/blog/"
public_folder: "/blog/images"

i18n:
    structure: "multiple_folders"
    locales: ["en", "fr"]
    default_locale: "en"

collections:
    - name: "services"
      i18n: true
      label: "My services"
      folder: "src/content/services"
      create: true
      delete: true
      fields:
        - name: "title"
          widget: "string"
          label: "Title"
          i18n: true
        - name: "position"
          widget: "number"
          label: "Position"
          i18n: duplicate
        - name: "logo"
          widget: "select"
          options: [
            "audit",
            "perf",
            "cto",
            "mvp",
            "upgrade",
            "refacto",
            "construction",
            "users"
          ]
          i18n: duplicate
        - name: "intro"
          widget: "markdown"
          label: "Intro"
          i18n: true

    - name: "posts"
      i18n: duplicate
      label: "Blog Posts"
      folder: "src/content/blog"
      create: true
      delete: true
      fields:
          - name: "title"
            widget: "string"
            label: "Post Title"
          - label: "Published"
            name: "published"
            widget: "boolean"
          - label: "Tags"
            name: "tags"
            widget: "list"
          - label: "Image"
            name: "image"
            widget: "object"
            required: false
            fields:
                - { label: Source, name: src, widget: image }
                - { label: Alt Text, name: alt, widget: string }
          - label: "Snippet"
            name: "snippet"
            widget: "text"
          - label: "Publish Date"
            name: "pubDate"
            widget: "datetime"
            format: "YYYY-MM-DD HH:mm"
          - label: "Category"
            name: "category"
            widget: "select"
            options: [
              "Tutorials",
              "News",
              "Reviews",
              "Frameworks",
              "Code sharing",
              "Tips",
              "Others"
            ]
          - name: "body"
            widget: "markdown"
            label: "Post Body"
