local_backend: true

logo_url: /images/logo/logo-2.png

backend:
    name: "github"
    repo: loicginoux/loicginoux
    branch: master
    base_url: https://sveltia-cms-auth.lginoux.workers.dev
    automatic_deployments: false

media_folder: "public/images/blog/"
public_folder: "/blog/images"

# i18n:
#     structure: "multiple_folders"
#     locales: ["en"]
#     default_locale: "en"

collections:
    - name: "posts"
      i18n: true
      label: "Blog Posts"
      folder: "src/content/blog"
      create: true
      delete: true
      fields:
          - name: "title"
            widget: "string"
            label: "Post Title"
            i18n: true
          - label: "Published"
            name: "published"
            widget: "boolean"
            i18n: "duplicate"
          - label: "Tags"
            name: "tags"
            widget: "list"
            i18n: true
          - label: "Image"
            name: "image"
            widget: "object"
            i18n: true
            required: false

            fields:
                - { label: Source, name: src, widget: image, i18n: "duplicate" }
                - { label: Alt Text, name: alt, widget: string, i18n: true }
          - label: "Snippet"
            name: "snippet"
            widget: "text"
            i18n: true
          - label: "Publish Date"
            name: "pubDate"
            widget: "datetime"
            format: "YYYY-MM-DD HH:mm"
            i18n: "duplicate"
          - label: "Category"
            name: "category"
            widget: "select"
            options: [
              "Tutorials",
              "News",
              "Reviews",
              "Frameworks",
              "Code sharing",
              "Tips",
              "Others"
            ]
            i18n: "duplicate"
          - name: "body"
            widget: "markdown"
            label: "Post Body"
            i18n: true
